title: Peter Forret
email: peter@forret.com
description: because eloquence is, like, whatever
baseurl: "/"
url: ""
twitter_username: pforret
github_username:  pforret

highlighter:      rouge
permalink:        pretty

paginate:         10

author:
  name:           'Peter Forret'
  url:            https://twitter.com/pforret

# Build settings
plugins:
#  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - hyde
  - .idea/

collections:
  categories:
    output: true
    permalink: /category

  tags:
    output: true
    permalink: /tag
